### PR TITLE
Move to proj-sys and proj.4 v5

### PR DESCRIPTION
**Pull request by urschrei**
With the surprising release (after about 23 years) of proj.4 v5, and my blowing-the-cobwebs-off PR from yesterday (#5), I thought I'd publish a [`proj-sys`](https://crates.io/crates/proj-sys) crate (generated using `bindgen`), and use it as the basis for this.
Currently, the API contains a very breaking change, because proj.4 performs operations differently now: it distinguishes between _projection_ (conversions from geodetic to projected coordinates) and _conversion_ (conversions between projected coordinate systems, usually within the same datum / reference frame). The latter uses a concept proj.4 calls the [`pipeline`](http://proj4.org/operations/pipeline.html), which allows for multi-step operations to achieve almost any kind of conversion, as opposed to the old system, which only allowed the specification of `from` and `to` projections.
This change is mirrored in the rust-proj API: for simple (inverse) projection from/to geodetic coordinates, there's `project`, and for conversions and transformations there's `convert`.
I'm not 100% sold on the API, because it feels a bit less flexible than the old one: you could specify different destination projections, and re-use the `Proj` struct. Using the new API, you have to specify everything up front, but you have a great deal more flexibility in terms of what you can do with it (see the `conversion` example). The conversion function also returns a `Result` now, and errors are implemented using `Failure`.
<s>Anyway, this is currently WIP until I figure out how to detect errors using the new API.</s>

### CODE REVIEW

**Comment by urschrei** [comment]
Update: error handling works now.

**Comment by urschrei** [comment]
Ugh bindgen is choking on multiple definitions after I `included` the legacy API so I could look up errors. Hrmm.

File: src/proj.rs [hunk 1]
```diff
@@ -94,36 +194,103 @@ mod test {
...
+            .convert(Point::new(4760096.421921, 3744293.729449))
+            .unwrap();
+        assert_almost_eq(t.x(), 1450880.29);
+        assert_almost_eq(t.y(), 1141263.01);
+    }
+    #[test]
+    #[should_panic]
+    // Test that instantiation fails wth bad proj string input
+    fn test_init_error() {
+        let _ = Proj::new("ugh").unwrap();
```
Comment (frewsxcv) [inline src/proj.rs]: alternatively

```rust
assert!(Proj::new("ugh").is_none());
```

**Comment by frewsxcv** [comment]
@urschrei just gave you review permissions for the repo

**Comment by urschrei** [comment]
bors r=frewsxcv
